### ISSUE TITLE
Cannot find module './ngfactory/app/server-app.module.ngfactory'. while publishing

### ISSUE THREAD

**Issue by cristiancamiloperezlopez** [MarkPieszak/aspnetcore-angular2-universal#297]
Hi Mark,

I'm having the error:

![image](https://user-images.githubusercontent.com/25587867/26929325-d27038e0-4c1e-11e7-892e-58501ff3b0c1.png)

I read here that I should ignore the error but I do not know how

Visual Studio has been upgraded and since that is presented to the error when executing or publishing the project

![image](https://user-images.githubusercontent.com/25587867/26929356-efe7faca-4c1e-11e7-889a-2ff59c4f50d4.png)

![image](https://user-images.githubusercontent.com/25587867/26929387-1c8c3866-4c1f-11e7-9a04-cee815c50ea9.png)

How can I do to skip this error ? Thanks

**Comment by isaac2004** [comment]
#272 I don't have this issue on publish, just a TS error. Does not stop Build or Webpack

**Comment by cristiancamiloperezlopez** [comment]
In my case, after upgrading visual studio 2017 to 15.2 (26430.12)

![image](https://user-images.githubusercontent.com/25587867/26944601-ca157a0e-4c4e-11e7-996b-e61f582523a7.png)

**Comment by MarkPieszak** [comment]
What errors appear in the Output console in VS?

**Comment by cristiancamiloperezlopez** [comment]
Hi Mark,

![image](https://user-images.githubusercontent.com/25587867/26945282-db82a8b4-4c50-11e7-8489-732a01e4111b.png)

**Comment by peterdobson** [comment]
Do you get more useful error information when you  run (via the command line at project root):

npm run build:aot

I was able to solve solve similar errors on publishing by changing component variables from private to public etc and found out about these by running the above command.

**Comment by isaac2004** [comment]
You can also install WebPackTaskRunner and run Build Dev to get more verbose output

**Comment by MarkPieszak** [comment]
Have you tried the npm run build:AoT as Peter mentioned?
There must be some kind of error whe statically analyzing the code for pre compilation. @cristiancamiloperezlopez

**Comment by danielnajera** [comment]
I getting the same issue, here is the log file:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:aot' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'prebuild:aot', 'build:aot', 'postbuild:aot' ]
5 info lifecycle angular4-aspnetcore-universal@1.0.0-rc3~prebuild:aot: angular4-aspnetcore-universal@1.0.0-rc3
6 silly lifecycle angular4-aspnetcore-universal@1.0.0-rc3~prebuild:aot: no script for prebuild:aot, continuing
7 info lifecycle angular4-aspnetcore-universal@1.0.0-rc3~build:aot: angular4-aspnetcore-universal@1.0.0-rc3
8 verbose lifecycle angular4-aspnetcore-universal@1.0.0-rc3~build:aot: unsafe-perm in lifecycle true
9 verbose lifecycle angular4-aspnetcore-universal@1.0.0-rc3~build:aot: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Daniel\Documents\Visual Studio 2017\Projects\TSMS\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\nodejs\;C:\Users\Daniel\AppData\Local\Microsoft\WindowsApps;C:\Users\Daniel\AppData\Roaming\npm
10 verbose lifecycle angular4-aspnetcore-universal@1.0.0-rc3~build:aot: CWD: C:\Users\Daniel\Documents\Visual Studio 2017\Projects\TSMS
11 silly lifecycle angular4-aspnetcore-universal@1.0.0-rc3~build:aot: Args: [ '/d /s /c',
11 silly lifecycle   'webpack --env.aot --env.client & webpack --env.aot --env.server' ]
12 silly lifecycle angular4-aspnetcore-universal@1.0.0-rc3~build:aot: Returned: code: 2  signal: null
13 info lifecycle angular4-aspnetcore-universal@1.0.0-rc3~build:aot: Failed to exec build:aot script
14 verbose stack Error: angular4-aspnetcore-universal@1.0.0-rc3 build:aot: `webpack --env.aot --env.client & webpack --env.aot --env.server`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid angular4-aspnetcore-universal@1.0.0-rc3
16 verbose cwd C:\Users\Daniel\Documents\Visual Studio 2017\Projects\TSMS
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:aot"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error angular4-aspnetcore-universal@1.0.0-rc3 build:aot: `webpack --env.aot --env.client & webpack --env.aot --env.server`
22 error Exit status 2
23 error Failed at the angular4-aspnetcore-universal@1.0.0-rc3 build:aot script 'webpack --env.aot --env.client & webpack --env.aot --env.server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular4-aspnetcore-universal package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack --env.aot --env.client & webpack --env.aot --env.server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular4-aspnetcore-universal
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular4-aspnetcore-universal
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by cristiancamiloperezlopez** [comment]
Thank you @peterdobson 
It was exactly what you said

Had
`Private translate: TranslateService,`
And it is
`Public translate: TranslateService,`

In my component
