### ISSUE TITLE
SignalR error?

### ISSUE THREAD

**Issue by larlew** [MarkPieszak/aspnetcore-angular2-universal#370]
I almost have this project running (VS 2017 15.3) but I am getting this SignalR error. 
Any ideas?

--------------
ERROR in C:/code/aspnetcore-angular-universal-master/aspnetcore-angular-universal-master/aspnetcore-angular/client/app/shared/route.resolver.ts (7,14): Class 'ConnectionResolver' incorrectly implements interface 'Resolve<SignalRConnection>'.
  Types of property 'resolve' are incompatible.
    Type '() => Promise<ISignalRConnection>' is not assignable to type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => SignalRConnection | Observable<Sig...'.
      Type 'Promise<ISignalRConnection>' is not assignable to type 'SignalRConnection | Observable<SignalRConnection> | Promise<SignalRConnection>'.
        Type 'Promise<ISignalRConnection>' is not assignable to type 'Promise<SignalRConnection>'.
          Type 'ISignalRConnection' is not assignable to type 'SignalRConnection'.
            Property '_status' is missing in type 'ISignalRConnection'.
ERROR in C:/code/aspnetcore-angular-universal-master/aspnetcore-angular-universal-master/aspnetcore-angular/client/main.server.ts (16,46): Cannot find name 'BootFuncParams'.

**Comment by larlew** [comment]
NVM.  I found a solution from an older issue. 
-- open the package.json file and update the following to "ng2-signalr": "2.0.4"  -- worked for me.

**Comment by larlew** [comment]
sigh. correction. Did NOT work.

**Comment by MarkPieszak** [comment]
Did you upgrade your TypeScript version to `2.4.x`, you want to keep it at `2.3.4` for now. Angular isn't fully working with 2.4.x just yet, but it will sometime soon.

Let me know!

**Comment by larlew** [comment]
I fixed the SignalR thing by fixing the interface name.( ISignalRConnection)

Now I just have this single error:
C:/code/aspnetcore-angular-universal-master/aspnetcore-angular-universal-master/aspnetcore-angular/client/main.server.ts (16,46): Cannot find name 'BootFuncParams'.

**Comment by MarkPieszak** [comment]
Give it a shot now with dotnet code 2.0 installed, wasn't able to reproduce it. Might be some config you have on your machine? Closing out for now.
